# -*- coding: utf-8 -*-
"""Football / Soccer attempt trend analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JoI-moJ8hNFntaPo4ThzJNwcO_dnsaXb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

exp_df = pd.read_csv('/content/drive/My Drive/datasets_36492_55620_stats.csv')

exp_df.head()

exp_df.info()

"""It can be noted that the data set consists of the performance of some football clubs in a league over the years.

So, we will study their individual trends first.
"""

exp_df_sorted = exp_df.sort_values(by=['team', 'season'])

def unique_vals(col):
    print(col)
    arr = list(exp_df[col].unique())
    arr.sort()
    print(arr)
    return arr

cols = list(exp_df.columns)

teams = unique_vals('team')

for team in teams:
    x = exp_df_sorted.loc[exp_df_sorted['team']==team]
    print(x)

"""Selecting the teams which have played all 12 seasons"""

viz_teams = ['Arsenal','Chelsea','Everton','Liverpool','Manchester City','Manchester United','Tottenham Hotspur']

"""comparing total scoring attempts and on-target scoring attempts"""

features = ['total_scoring_att','ontarget_scoring_att']
for team in viz_teams:
    for feature in features:
        print(team)
        x = exp_df_sorted.loc[exp_df_sorted['team']==team]
        y = pd.DataFrame(x[feature])
        y['season'] = x['season']
        y = y.reset_index(drop=True,inplace=False)
        plt.figure(figsize=(14,6))
        plt.plot(y['season'],y[feature])

"""It can be noted that the total scoring attempts and on-target scoring attempts observe very similar trends.

**It can be deduced that more the attempts, more is the number of on target attempts**
"""